all:  score parts

score:  ScoreMvtIII.pdf ScoreNT.pdf

parts:  Flute1.pdf Flute2.pdf Oboe.pdf Bassoon.pdf Clarinet1.pdf Clarinet2.pdf Clarinet3.pdf BassClarinet.pdf AltoSax1.pdf AltoSax2.pdf TenorSax.pdf BariSax.pdf Trumpet1.pdf Trumpet2.pdf Trumpet3.pdf Horn1.pdf Horn2.pdf Trombone1.pdf Trombone2.pdf Trombone3.pdf Baritone.pdf BaritoneTC.pdf StringBass.pdf Tuba.pdf Percussion.pdf Timpani.pdf

ScoreMvtIII.pdf: ScoreMvtIII.ly
	lilypond ScoreMvtIII.ly

ScoreNT.pdf: ScoreNT.ly
	lilypond ScoreNT.ly

Flute1.pdf: Flute1.ly
	lilypond Flute1.ly

Flute2.pdf: Flute2.ly
	lilypond Flute2.ly

Oboe.pdf: Oboe.ly
	lilypond Oboe.ly

Bassoon.pdf: Bassoon.ly
	lilypond Bassoon.ly

Clarinet1.pdf: Clarinet1.ly
	lilypond Clarinet1.ly

Clarinet2.pdf: Clarinet2.ly
	lilypond Clarinet2.ly

Clarinet3.pdf: Clarinet3.ly
	lilypond Clarinet3.ly

BassClarinet.pdf: BassClarinet.ly
	lilypond BassClarinet.ly

AltoSax1.pdf: AltoSax1.ly
	lilypond AltoSax1.ly

AltoSax2.pdf: AltoSax2.ly
	lilypond AltoSax2.ly

TenorSax.pdf: TenorSax.ly
	lilypond TenorSax.ly

BariSax.pdf: BariSax.ly
	lilypond BariSax.ly

Trumpet1.pdf: Trumpet1.ly
	lilypond Trumpet1.ly

Trumpet2.pdf: Trumpet2.ly
	lilypond Trumpet2.ly

Trumpet3.pdf: Trumpet3.ly
	lilypond Trumpet3.ly

Horn1.pdf: Horn1.ly
	lilypond Horn1.ly

Horn2.pdf: Horn2.ly
	lilypond Horn2.ly

Trombone1.pdf: Trombone1.ly
	lilypond Trombone1.ly

Trombone2.pdf: Trombone2.ly
	lilypond Trombone2.ly

Trombone3.pdf: Trombone3.ly
	lilypond Trombone3.ly

Baritone.pdf: Baritone.ly
	lilypond Baritone.ly

BaritoneTC.pdf: BaritoneTC.ly
	lilypond BaritoneTC.ly

StringBass.pdf: StringBass.ly
	lilypond StringBass.ly

Tuba.pdf: Tuba.ly
	lilypond Tuba.ly

Percussion.pdf: Percussion.ly
	lilypond Percussion.ly

Timpani.pdf: Timpani.ly
	lilypond Timpani.ly

ScoreMvtIII.ly: defs.lyi

ScoreMvtIII.ly: Flute1MvtIII.lyi

ScoreMvtIII.ly: Flute2MvtIII.lyi

ScoreMvtIII.ly: OboeMvtIII.lyi

ScoreMvtIII.ly: BassoonMvtIII.lyi

ScoreMvtIII.ly: Clarinet1MvtIII.lyi

ScoreMvtIII.ly: Clarinet2MvtIII.lyi

ScoreMvtIII.ly: Clarinet3MvtIII.lyi

ScoreMvtIII.ly: BassClarinetMvtIII.lyi

ScoreMvtIII.ly: AltoSax1MvtIII.lyi

ScoreMvtIII.ly: AltoSax2MvtIII.lyi

ScoreMvtIII.ly: TenorSaxMvtIII.lyi

ScoreMvtIII.ly: BariSaxMvtIII.lyi

ScoreMvtIII.ly: Trumpet1MvtIII.lyi

ScoreMvtIII.ly: Trumpet2MvtIII.lyi

ScoreMvtIII.ly: Trumpet3MvtIII.lyi

ScoreMvtIII.ly: Horn1MvtIII.lyi

ScoreMvtIII.ly: Horn2MvtIII.lyi

ScoreMvtIII.ly: Trombone1MvtIII.lyi

ScoreMvtIII.ly: Trombone2MvtIII.lyi

ScoreMvtIII.ly: Trombone3MvtIII.lyi

ScoreMvtIII.ly: BaritoneMvtIII.lyi

ScoreMvtIII.ly: TubaMvtIII.lyi

ScoreMvtIII.ly: PercussionMvtIII.lyi

ScoreMvtIII.ly: TimpaniMvtIII.lyi

ScoreNT.ly: defs.lyi

ScoreNT.ly: Flute1MvtIII.lyi

ScoreNT.ly: Flute2MvtIII.lyi

ScoreNT.ly: OboeMvtIII.lyi

ScoreNT.ly: BassoonMvtIII.lyi

ScoreNT.ly: Clarinet1MvtIII.lyi

ScoreNT.ly: Clarinet2MvtIII.lyi

ScoreNT.ly: Clarinet3MvtIII.lyi

ScoreNT.ly: BassClarinetMvtIII.lyi

ScoreNT.ly: AltoSax1MvtIII.lyi

ScoreNT.ly: AltoSax2MvtIII.lyi

ScoreNT.ly: TenorSaxMvtIII.lyi

ScoreNT.ly: BariSaxMvtIII.lyi

ScoreNT.ly: Trumpet1MvtIII.lyi

ScoreNT.ly: Trumpet2MvtIII.lyi

ScoreNT.ly: Trumpet3MvtIII.lyi

ScoreNT.ly: Horn1MvtIII.lyi

ScoreNT.ly: Horn2MvtIII.lyi

ScoreNT.ly: Trombone1MvtIII.lyi

ScoreNT.ly: Trombone2MvtIII.lyi

ScoreNT.ly: Trombone3MvtIII.lyi

ScoreNT.ly: BaritoneMvtIII.lyi

ScoreNT.ly: TubaMvtIII.lyi

ScoreNT.ly: PercussionMvtIII.lyi

ScoreNT.ly: TimpaniMvtIII.lyi

Flute1.ly: defs.lyi

Flute1.ly: Flute1MvtIII.lyi

Flute1.ly: Part.lyi

Flute2.ly: defs.lyi

Flute2.ly: Flute2MvtIII.lyi

Flute2.ly: Part.lyi

Oboe.ly: defs.lyi

Oboe.ly: OboeMvtIII.lyi

Oboe.ly: Part.lyi

Bassoon.ly: defs.lyi

Bassoon.ly: BassoonMvtIII.lyi

Bassoon.ly: Part.lyi

Clarinet1.ly: defs.lyi

Clarinet1.ly: Clarinet1MvtIII.lyi

Clarinet1.ly: Part.lyi

Clarinet2.ly: defs.lyi

Clarinet2.ly: Clarinet2MvtIII.lyi

Clarinet2.ly: Part.lyi

Clarinet3.ly: defs.lyi

Clarinet3.ly: Clarinet3MvtIII.lyi

Clarinet3.ly: Part.lyi

BassClarinet.ly: defs.lyi

BassClarinet.ly: BassClarinetMvtIII.lyi

BassClarinet.ly: Part.lyi

AltoSax1.ly: defs.lyi

AltoSax1.ly: AltoSax1MvtIII.lyi

AltoSax1.ly: Part.lyi

AltoSax2.ly: defs.lyi

AltoSax2.ly: AltoSax2MvtIII.lyi

AltoSax2.ly: Part.lyi

TenorSax.ly: defs.lyi

TenorSax.ly: TenorSaxMvtIII.lyi

TenorSax.ly: Part.lyi

BariSax.ly: defs.lyi

BariSax.ly: BariSaxMvtIII.lyi

BariSax.ly: Part.lyi

Trumpet1.ly: defs.lyi

Trumpet1.ly: Trumpet1MvtIII.lyi

Trumpet1.ly: Part.lyi

Trumpet2.ly: defs.lyi

Trumpet2.ly: Trumpet2MvtIII.lyi

Trumpet2.ly: Part.lyi

Trumpet3.ly: defs.lyi

Trumpet3.ly: Trumpet3MvtIII.lyi

Trumpet3.ly: Part.lyi

Horn1.ly: defs.lyi

Horn1.ly: Horn1MvtIII.lyi

Horn1.ly: Part.lyi

Horn2.ly: defs.lyi

Horn2.ly: Horn2MvtIII.lyi

Horn2.ly: Part.lyi

Trombone1.ly: defs.lyi

Trombone1.ly: Trombone1MvtIII.lyi

Trombone1.ly: Part.lyi

Trombone2.ly: defs.lyi

Trombone2.ly: Trombone2MvtIII.lyi

Trombone2.ly: Part.lyi

Trombone3.ly: defs.lyi

Trombone3.ly: Trombone3MvtIII.lyi

Trombone3.ly: Part.lyi

Baritone.ly: defs.lyi

Baritone.ly: BaritoneMvtIII.lyi

Baritone.ly: Part.lyi

BaritoneTC.ly: defs.lyi

BaritoneTC.ly: BaritoneMvtIII.lyi

BaritoneTC.ly: Part.lyi

StringBass.ly: defs.lyi

StringBass.ly: TubaMvtIII.lyi

StringBass.ly: Part.lyi

Tuba.ly: defs.lyi

Tuba.ly: TubaMvtIII.lyi

Tuba.ly: Part.lyi

Percussion.ly: defs.lyi

Percussion.ly: PercussionMvtIII.lyi

Percussion.ly: Part.lyi

Timpani.ly: defs.lyi

Timpani.ly: TimpaniMvtIII.lyi

Timpani.ly: Part.lyi

Flute1MvtIII.lyi: defs.lyi

Flute2MvtIII.lyi: defs.lyi

OboeMvtIII.lyi: defs.lyi

BassoonMvtIII.lyi: defs.lyi

Clarinet1MvtIII.lyi: defs.lyi

Clarinet2MvtIII.lyi: defs.lyi

Clarinet3MvtIII.lyi: defs.lyi

BassClarinetMvtIII.lyi: defs.lyi

AltoSax1MvtIII.lyi: defs.lyi

AltoSax2MvtIII.lyi: defs.lyi

TenorSaxMvtIII.lyi: defs.lyi

BariSaxMvtIII.lyi: defs.lyi

Trumpet1MvtIII.lyi: defs.lyi

Trumpet2MvtIII.lyi: defs.lyi

Trumpet3MvtIII.lyi: defs.lyi

Horn1MvtIII.lyi: defs.lyi

Horn2MvtIII.lyi: defs.lyi

Trombone1MvtIII.lyi: defs.lyi

Trombone2MvtIII.lyi: defs.lyi

Trombone3MvtIII.lyi: defs.lyi

BaritoneMvtIII.lyi: defs.lyi

TubaMvtIII.lyi: defs.lyi

PercussionMvtIII.lyi: defs.lyi

TimpaniMvtIII.lyi: defs.lyi

Part.lyi: defs.lyi

