all:  score parts

score:  Score.pdf ScoreNT.pdf

parts:  Flute1.pdf Flute2.pdf Oboe.pdf Bassoon.pdf Clarinet1.pdf Clarinet2.pdf Clarinet3.pdf BassClarinet.pdf AltoSax1.pdf AltoSax2.pdf TenorSax.pdf BariSax.pdf Trumpet1.pdf Trumpet2.pdf Trumpet3.pdf Horn1.pdf Horn2.pdf Trombone1.pdf Trombone2.pdf Trombone3.pdf Baritone.pdf BaritoneTC.pdf StringBass.pdf Tuba.pdf Percussion.pdf Timpani.pdf

Score.pdf: defs.lyi Outline.lyi Score.ly Flute1.lyi Flute2.lyi Oboe.lyi Bassoon.lyi Clarinet1.lyi Clarinet2.lyi Clarinet3.lyi BassClarinet.lyi AltoSax1.lyi AltoSax2.lyi TenorSax.lyi BariSax.lyi Trumpet1.lyi Trumpet2.lyi Trumpet3.lyi Horn1.lyi Horn2.lyi Trombone1.lyi Trombone2.lyi Trombone3.lyi Baritone.lyi Tuba.lyi Percussion.lyi Timpani.lyi
	lilypond Score.ly

ScoreNT.pdf: defs.lyi Outline.lyi ScoreNT.ly Flute1.lyi Flute2.lyi Oboe.lyi Bassoon.lyi Clarinet1.lyi Clarinet2.lyi Clarinet3.lyi BassClarinet.lyi AltoSax1.lyi AltoSax2.lyi TenorSax.lyi BariSax.lyi Trumpet1.lyi Trumpet2.lyi Trumpet3.lyi Horn1.lyi Horn2.lyi Trombone1.lyi Trombone2.lyi Trombone3.lyi Baritone.lyi Tuba.lyi Percussion.lyi Timpani.lyi
	lilypond ScoreNT.ly

Flute1.pdf: defs.lyi Outline.lyi Part.lyi Flute1.ly Flute1.lyi
	lilypond Flute1.ly

Flute2.pdf: defs.lyi Outline.lyi Part.lyi Flute2.ly Flute2.lyi
	lilypond Flute2.ly

Oboe.pdf: defs.lyi Outline.lyi Part.lyi Oboe.ly Oboe.lyi
	lilypond Oboe.ly

Bassoon.pdf: defs.lyi Outline.lyi Part.lyi Bassoon.ly Bassoon.lyi
	lilypond Bassoon.ly

Clarinet1.pdf: defs.lyi Outline.lyi Part.lyi Clarinet1.ly Clarinet1.lyi
	lilypond Clarinet1.ly

Clarinet2.pdf: defs.lyi Outline.lyi Part.lyi Clarinet2.ly Clarinet2.lyi
	lilypond Clarinet2.ly

Clarinet3.pdf: defs.lyi Outline.lyi Part.lyi Clarinet3.ly Clarinet3.lyi
	lilypond Clarinet3.ly

BassClarinet.pdf: defs.lyi Outline.lyi Part.lyi BassClarinet.ly BassClarinet.lyi
	lilypond BassClarinet.ly

AltoSax1.pdf: defs.lyi Outline.lyi Part.lyi AltoSax1.ly AltoSax1.lyi
	lilypond AltoSax1.ly

AltoSax2.pdf: defs.lyi Outline.lyi Part.lyi AltoSax2.ly AltoSax2.lyi
	lilypond AltoSax2.ly

TenorSax.pdf: defs.lyi Outline.lyi Part.lyi TenorSax.ly TenorSax.lyi
	lilypond TenorSax.ly

BariSax.pdf: defs.lyi Outline.lyi Part.lyi BariSax.ly BariSax.lyi
	lilypond BariSax.ly

Trumpet1.pdf: defs.lyi Outline.lyi Part.lyi Trumpet1.ly Trumpet1.lyi
	lilypond Trumpet1.ly

Trumpet2.pdf: defs.lyi Outline.lyi Part.lyi Trumpet2.ly Trumpet2.lyi
	lilypond Trumpet2.ly

Trumpet3.pdf: defs.lyi Outline.lyi Part.lyi Trumpet3.ly Trumpet3.lyi
	lilypond Trumpet3.ly

Horn1.pdf: defs.lyi Outline.lyi Part.lyi Horn1.ly Horn1.lyi
	lilypond Horn1.ly

Horn2.pdf: defs.lyi Outline.lyi Part.lyi Horn2.ly Horn2.lyi
	lilypond Horn2.ly

Trombone1.pdf: defs.lyi Outline.lyi Part.lyi Trombone1.ly Trombone1.lyi
	lilypond Trombone1.ly

Trombone2.pdf: defs.lyi Outline.lyi Part.lyi Trombone2.ly Trombone2.lyi
	lilypond Trombone2.ly

Trombone3.pdf: defs.lyi Outline.lyi Part.lyi Trombone3.ly Trombone3.lyi
	lilypond Trombone3.ly

Baritone.pdf: defs.lyi Outline.lyi Part.lyi Baritone.ly Baritone.lyi
	lilypond Baritone.ly

BaritoneTC.pdf: defs.lyi Outline.lyi Part.lyi BaritoneTC.ly Baritone.lyi
	lilypond BaritoneTC.ly

StringBass.pdf: defs.lyi Outline.lyi Part.lyi StringBass.ly Tuba.lyi
	lilypond StringBass.ly

Tuba.pdf: defs.lyi Outline.lyi Part.lyi Tuba.ly Tuba.lyi
	lilypond Tuba.ly

Percussion.pdf: defs.lyi Outline.lyi Part.lyi Percussion.ly Percussion.lyi
	lilypond Percussion.ly

Timpani.pdf: defs.lyi Outline.lyi Part.lyi Timpani.ly Timpani.lyi
	lilypond Timpani.ly
