all:  score parts

score:  Score.pdf ScoreNT.pdf

parts:  Flute1.pdf Flute2.pdf Oboe.pdf Bassoon.pdf Clarinet1.pdf Clarinet2.pdf Clarinet3.pdf BassClarinet.pdf AltoSax1.pdf AltoSax2.pdf TenorSax.pdf BariSax.pdf Trumpet1.pdf Trumpet2.pdf Trumpet3.pdf Horn1.pdf Horn2.pdf Trombone1.pdf Trombone2.pdf Trombone3.pdf Baritone.pdf BaritoneTC.pdf StringBass.pdf Tuba.pdf Percussion.pdf Timpani.pdf

Score.pdf: Score.ly
	lilypond Score.ly

ScoreNT.pdf: ScoreNT.ly
	lilypond ScoreNT.ly

Flute1.pdf: Flute1.ly
	lilypond Flute1.ly

Flute2.pdf: Flute2.ly
	lilypond Flute2.ly

Oboe.pdf: Oboe.ly
	lilypond Oboe.ly

Bassoon.pdf: Bassoon.ly
	lilypond Bassoon.ly

Clarinet1.pdf: defs.lyi Outline.lyi Part.lyi Clarinet1.ly
	lilypond Clarinet1.ly

Clarinet2.pdf: Clarinet2.ly
	lilypond Clarinet2.ly

Clarinet3.pdf: Clarinet3.ly
	lilypond Clarinet3.ly

BassClarinet.pdf: BassClarinet.ly
	lilypond BassClarinet.ly

AltoSax1.pdf: AltoSax1.ly
	lilypond AltoSax1.ly

AltoSax2.pdf: AltoSax2.ly
	lilypond AltoSax2.ly

TenorSax.pdf: TenorSax.ly
	lilypond TenorSax.ly

BariSax.pdf: BariSax.ly
	lilypond BariSax.ly

Trumpet1.pdf: Trumpet1.ly
	lilypond Trumpet1.ly

Trumpet2.pdf: Trumpet2.ly
	lilypond Trumpet2.ly

Trumpet3.pdf: Trumpet3.ly
	lilypond Trumpet3.ly

Horn1.pdf: Horn1.ly
	lilypond Horn1.ly

Horn2.pdf: Horn2.ly
	lilypond Horn2.ly

Trombone1.pdf: Trombone1.ly
	lilypond Trombone1.ly

Trombone2.pdf: Trombone2.ly
	lilypond Trombone2.ly

Trombone3.pdf: Trombone3.ly
	lilypond Trombone3.ly

Baritone.pdf: Baritone.ly
	lilypond Baritone.ly

BaritoneTC.pdf: BaritoneTC.ly
	lilypond BaritoneTC.ly

StringBass.pdf: StringBass.ly
	lilypond StringBass.ly

Tuba.pdf: Tuba.ly
	lilypond Tuba.ly

Percussion.pdf: Percussion.ly
	lilypond Percussion.ly

Timpani.pdf: Timpani.ly
	lilypond Timpani.ly

Score.ly: defs.lyi

Score.ly: Outline.lyi

Score.ly: Flute1.lyi

Score.ly: Flute2.lyi

Score.ly: Oboe.lyi

Score.ly: Bassoon.lyi

Score.ly: Clarinet1.lyi

Score.ly: Clarinet2.lyi

Score.ly: Clarinet3.lyi

Score.ly: BassClarinet.lyi

Score.ly: AltoSax1.lyi

Score.ly: AltoSax2.lyi

Score.ly: TenorSax.lyi

Score.ly: BariSax.lyi

Score.ly: Trumpet1.lyi

Score.ly: Trumpet2.lyi

Score.ly: Trumpet3.lyi

Score.ly: Horn1.lyi

Score.ly: Horn2.lyi

Score.ly: Trombone1.lyi

Score.ly: Trombone2.lyi

Score.ly: Trombone3.lyi

Score.ly: Baritone.lyi

Score.ly: Tuba.lyi

Score.ly: Percussion.lyi

Score.ly: Timpani.lyi

ScoreNT.ly: defs.lyi

ScoreNT.ly: Outline.lyi

ScoreNT.ly: Flute1.lyi

ScoreNT.ly: Flute2.lyi

ScoreNT.ly: Oboe.lyi

ScoreNT.ly: Bassoon.lyi

ScoreNT.ly: Clarinet1.lyi

ScoreNT.ly: Clarinet2.lyi

ScoreNT.ly: Clarinet3.lyi

ScoreNT.ly: BassClarinet.lyi

ScoreNT.ly: AltoSax1.lyi

ScoreNT.ly: AltoSax2.lyi

ScoreNT.ly: TenorSax.lyi

ScoreNT.ly: BariSax.lyi

ScoreNT.ly: Trumpet1.lyi

ScoreNT.ly: Trumpet2.lyi

ScoreNT.ly: Trumpet3.lyi

ScoreNT.ly: Horn1.lyi

ScoreNT.ly: Horn2.lyi

ScoreNT.ly: Trombone1.lyi

ScoreNT.ly: Trombone2.lyi

ScoreNT.ly: Trombone3.lyi

ScoreNT.ly: Baritone.lyi

ScoreNT.ly: Tuba.lyi

ScoreNT.ly: Percussion.lyi

ScoreNT.ly: Timpani.lyi

Flute1.ly: defs.lyi

Flute1.ly: Flute1.lyi

Flute1.ly: Part.lyi

Flute2.ly: defs.lyi

Flute2.ly: Flute2.lyi

Flute2.ly: Part.lyi

Oboe.ly: defs.lyi

Oboe.ly: Oboe.lyi

Oboe.ly: Part.lyi

Bassoon.ly: defs.lyi

Bassoon.ly: Bassoon.lyi

Bassoon.ly: Part.lyi

Clarinet1.ly: defs.lyi

Clarinet1.ly: Clarinet1.lyi

Clarinet1.ly: Part.lyi

Clarinet2.ly: defs.lyi

Clarinet2.ly: Clarinet2.lyi

Clarinet2.ly: Part.lyi

Clarinet3.ly: defs.lyi

Clarinet3.ly: Clarinet3.lyi

Clarinet3.ly: Part.lyi

BassClarinet.ly: defs.lyi

BassClarinet.ly: BassClarinet.lyi

BassClarinet.ly: Part.lyi

AltoSax1.ly: defs.lyi

AltoSax1.ly: AltoSax1.lyi

AltoSax1.ly: Part.lyi

AltoSax2.ly: defs.lyi

AltoSax2.ly: AltoSax2.lyi

AltoSax2.ly: Part.lyi

TenorSax.ly: defs.lyi

TenorSax.ly: TenorSax.lyi

TenorSax.ly: Part.lyi

BariSax.ly: defs.lyi

BariSax.ly: BariSax.lyi

BariSax.ly: Part.lyi

Trumpet1.ly: defs.lyi

Trumpet1.ly: Trumpet1.lyi

Trumpet1.ly: Part.lyi

Trumpet2.ly: defs.lyi

Trumpet2.ly: Trumpet2.lyi

Trumpet2.ly: Part.lyi

Trumpet3.ly: defs.lyi

Trumpet3.ly: Trumpet3.lyi

Trumpet3.ly: Part.lyi

Horn1.ly: defs.lyi

Horn1.ly: Horn1.lyi

Horn1.ly: Part.lyi

Horn2.ly: defs.lyi

Horn2.ly: Horn2.lyi

Horn2.ly: Part.lyi

Trombone1.ly: defs.lyi

Trombone1.ly: Trombone1.lyi

Trombone1.ly: Part.lyi

Trombone2.ly: defs.lyi

Trombone2.ly: Trombone2.lyi

Trombone2.ly: Part.lyi

Trombone3.ly: defs.lyi

Trombone3.ly: Trombone3.lyi

Trombone3.ly: Part.lyi

Baritone.ly: defs.lyi

Baritone.ly: Baritone.lyi

Baritone.ly: Part.lyi

BaritoneTC.ly: defs.lyi

BaritoneTC.ly: Baritone.lyi

BaritoneTC.ly: Part.lyi

StringBass.ly: defs.lyi

StringBass.ly: Tuba.lyi

StringBass.ly: Part.lyi

Tuba.ly: defs.lyi

Tuba.ly: Tuba.lyi

Tuba.ly: Part.lyi

Percussion.ly: defs.lyi

Percussion.ly: Percussion.lyi

Percussion.ly: Part.lyi

Timpani.ly: defs.lyi

Timpani.ly: Timpani.lyi

Timpani.ly: Part.lyi

Flute1.lyi: defs.lyi

Flute2.lyi: defs.lyi

Oboe.lyi: defs.lyi

Bassoon.lyi: defs.lyi

Clarinet1.lyi: defs.lyi

Clarinet2.lyi: defs.lyi

Clarinet3.lyi: defs.lyi

BassClarinet.lyi: defs.lyi

AltoSax1.lyi: defs.lyi

AltoSax2.lyi: defs.lyi

TenorSax.lyi: defs.lyi

BariSax.lyi: defs.lyi

Trumpet1.lyi: defs.lyi

Trumpet2.lyi: defs.lyi

Trumpet3.lyi: defs.lyi

Horn1.lyi: defs.lyi

Horn2.lyi: defs.lyi

Trombone1.lyi: defs.lyi

Trombone2.lyi: defs.lyi

Trombone3.lyi: defs.lyi

Baritone.lyi: defs.lyi

Tuba.lyi: defs.lyi

Percussion.lyi: defs.lyi

Timpani.lyi: defs.lyi

Part.lyi: defs.lyi Outline.lyi

