<?php
include "../common/helpers.php";

show_top();
show_main_top("<h2>How These Works Are Constructed</h2>\n<h4>A Guide to These Files</h4>", '../image.png');
?>

<p>
These directories can be categorized a few different ways.

<ol>
<li><h3>PDF Archive</h3>
I have some archives of PDF files, that have been reworked and cleaned up.
These are not checked in to Git so they don't appear in the repository.

<li><h3>Ensemble Works</h3>
Most of the work I've done is in this category.  These consist of Scores
and Parts that are all made from the same source files.<p>

The pdf files are created from the ly files in the root of each work.
The actual notes are in the parts/ directory, in lyi files.  Each part
has sequences named with the part name plus:
<ul>
<li>"Dyn" -- dynamics
<li>"Mks" -- marks
<li>"Scor" -- score
<li>"Cues" -- cues and other marks for the part only
<li>"Notes" -- the actual notes to be played
</ul>
These are then assembled into the building blocks of the pdf files, named with the part name plus:
<ul>
<li>"Score" -- Notes+Scor+Dyn plus base and outline, destined for the midi score and the non-transposed score
<li>"Cond" -- Notes+Scor+Mks plus base and outline, destined for the condensed score, if I can ever figure out how to do it
<li>key plus "Score" -- Notes+Scor+Dyn plus base and outline, destined for the full score, each part transposed
<li>key plus "Part" -- Notes+Cues+Dyn plus base, partbase and outline, destined for the part file, transposed
</ul>
Percussion is simpler since no key is involved.  For C instruments, the two score sequences are the same.<p>

The "base" sequence allows me to put in markups that affect every rendering, and is generally where I have the
basic measures, so that anywhere that doesn't follow this base throws and error.  The "outline" sequence has basic
marks, including time signatures, rehearsal marks, fermatas, caesuras, ritards, that sort of thing, and is rendered with every
individual part and once with each score.  The "partbase" sequence is mixed in with every part but no score, and
is rarely used.<p>

<b>Parts</b><p>

The source for all parts is written in the same key to allow for easily switching passages
to different instruments.  The "concertKey" setting allows me to transpose everything to a
new key, all at once.  The transpositions necessary for each instrument is done at the bottom of each part file.<p>

Each part has sequences for Notes, Dynamics, and Cues or NotCues ("Scor"), and Marks; and these are put together at the same
point the transposition is done, to produce a mixed seqence for the part and another for the score.
In some cases, markups might be moved from Notes to Cues to avoid problems with combining parts for the score.
Marks are only for markups going to the condensed score, so are not currently in use.<p>

The files with ly extension are rendered into pdf files.  Each part includes ../common/defs.lyi,
which is my library of useful things, not all of which will be used.  Then each part includes its
own lyi file, which has the sequences named above.  Finally each part includes single.lyi,
which includes outline.lyi, then lays things out on the page.<p>

<b>Scores</b><p>

The Score.ly file includes all the part lyi files, then lays out the full score.
There is also a ScoreNT.ly file to combine all the parts without transposing them.  This is just
for me to help understand how things fit together.
The ScoreMidi.ly file is there just to create the midi file, as the voltas (if any) have to be unfolded
to make it come out right, and the parts have to be combined differently.
The ScoreCond.ly file, if any, is an experimental project to generate a condensed score.<p>

<li><h3>Kathy Mar Songbook</h3>
This is my attempt to create a songbook of Kathy Mar's songs, arrange for
flexible ensemble.<p>

Everything specific to each song goes in the lyi file for that song.  This is included by the
tly file for that song, which is a file generated by makesong.py.  This file generates pdfs for
all the possible outputs:  SATB and MHB (melody/harmony/bass) for C (treble and bass clefs), F,
B&flat;, E&flat;; plus a GS for GrandStaff (piano), and a midi file.<p>

The songbook is constructed by concatenating the title page for that instrument plus the
relevant pdfs.  The title page currently has to be manually generated from the php file using
a browser, as I haven't figured out how to automate that yet.<p>

<li><h3>Common Files</h3>
These are files in the common/ directory, used by several works, intended to
make things easier for me.

<li><h3>Startup Script</h3>
This is a script in the start/ directory that I developed to take a list of instruments and splat them out
into files, so that I can get to writing notes more quickly.

</ol>

These works use <a href="https://github.com/kastdeur/lilydrum">https://github.com/kastdeur/lilydrum</a>
for extended drum markups.

</body>
</html>
